<html><head>
<meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
<title>&#9770; HacKeD By CyBeRKaNKa | HacKeD By Turan Army &#9770;</title>
<link href="http://i.hizliresim.com/0ng31R.png" rel="icon" type="image/png">
<meta content="&#9770; HacKeD By CyBeRKaNKa | HacKeD By Turan Army &#9770;" name="description">
<meta content="&#9770; HacKeD By CyBeRKaNKa | HacKeD By Turan Army &#9770;" name="keywords">
<meta content="&#9770; HacKeD By CyBeRKaNKa | HacKeD By Turan Army &#9770;" name="Abstract">
<meta name="&#9770; HacKeD By CyBeRKaNKa | HacKeD By Turan Army &#9770;">
<meta property="og:image" content="http://i.hizliresim.com/QMXM0G.jpg">
<meta http-equiv="refresh" content="172" />
<script language="Javascript">var msg1 = " Hacked By CyBeRKaNKa ";var speed=100;function ScrollTitle() {document.title=msg1;msg1=msg1.substring(1,msg1.length)+msg1.charAt(0);setTimeout("ScrollTitle()",speed);}ScrollTitle();</script>

<center>
<img style="width: 90px;" src="http://i.hizliresim.com/AJZLmz.gif">
<img style="width: 90px;" src="http://i.hizliresim.com/QM1aAv.gif">
<img style="width: 90px;" src="http://i.hizliresim.com/X420v0.gif">
<img style="width: 90px;" src="http://i.hizliresim.com/5VpgdD.gif">
<img style="width: 90px;" src="http://i.hizliresim.com/0Db1qR.gif">
<img style="width: 90px;" src="http://i.hizliresim.com/bbQr5G.gif">
<img style="width: 90px;" src="http://i.hizliresim.com/db4P57.gif">
<img style="width: 80px;" src="http://i.hizliresim.com/Gz1mP2.gif">
<img style="width: 80px;" src="http://i.hizliresim.com/OMdvVZ.gif">
<img style="width: 65px;" src="http://i.hizliresim.com/z4EjaY.gif">

<!--[if lt IE 7 ]><html class="ie ie6" lang="en-CA" prefix="og: http://ogp.me/ns#"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en-CA" prefix="og: http://ogp.me/ns#"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en-CA" prefix="og: http://ogp.me/ns#"> <![endif]-->
<!--[if IE 9 ]><html class="ie ie9" lang="en-CA" prefix="og: http://ogp.me/ns#"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <!--<![endif]-->

	<title> &#9770; HacKeD By CyBeRKaNKa | HacKeD By Turan Army &#9770; | </title>
	<meta name="description" content="&#9770; HacKeD By CyBeRKaNKa | HacKeD By Turan Army &#9770;">
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="profile" href="//gmpg.org/xfn/11">
	
<!-- Dynamic page generated in 1.601 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2015-08-08 13:00:08 -->

<!-- super cache -->

<head>

<script type="text/javascript">

</script>
<style id="page-skin-1" type="text/css">
#navbar-iframe {
display: none !important;
}
/*Basic Elements */
body {
background-color:white;background-image:url();background-repeat:repeat;
font-family:Verdana, "Trebuchet MS", Tahoma, Arial, Helvetica, sans-serif;
font-size:11px;line-height:18px;
color: green;
font-family: verdana;
font-size: 0.8em;
}
a:link, a:visited {
color: green;
text-decoration: none;
}
.header a  {
color: green;
text-decoration: none;
}
a:hover {
text-decoration: none;
color: black;
}
#container {
margin: 1px auto;
text-align: center;
width: 740px;
border:2px dotted #999;
background:transparent url()
 
;background-repeat:repeat;
padding:5px;
-moz-border-radius:10px;
-khtml-border-radius:10px;
-webkit-border-radius:10px;
border-radius:10px;
-moz-box-shadow: 0px 2px 5px 0px #f8f9b9;
}
/*Head Nav*/
ul#topnav {
margin: 10px 0 20px;
list-style: none;
font-size: 1.1em;
clear: both;
float: left;
width: 100%;
}
ul#topnav li{
margin: 0;
padding: 0;
overflow: hidden;
float: left;
height:40px;
}
ul#topnav a, ul#topnav span {
padding: 10px 20px;
float: left;
text-decoration: none;
color: green;
text-transform: uppercase;
clear: both;
height: 20px;
line-height: 20px;
background: black;
}
ul#topnav a {   color: red; }
ul#topnav span {
display: none;
}
ul#topnav.v2 span{
}
ul#topnav.v2 a{
color: red;
border: solid white 1px;
background-color:green;
}
#Attribution1 {
height:0px;
visibility:hidden;
display:none
}
.feed-links{
display:none;
}
#Blog1 {
height:0px;
visibility:hidden;
display:none
}
.cb-slideshow,
.cb-slideshow:after {
position: fixed;
width: 100%;
height: 100%;
top: 0px;
left: 0px;
z-index: -99;
}
.cb-slideshow:after {
content: '';
background: transparent url(http://i.hizliresim.com/9oWJE9.png) repeat top left;
}
.cb-slideshow li span {
width: 100%;
height: 100%;
position: absolute;
top: 0px;
left: 0px;
background-size: cover;
background-position: 50% 50%;
background-repeat: none;
opacity: 0;
z-index: 0;
-webkit-backface-visibility: hidden;
-webkit-animation: imageAnimation 36s linear infinite 0s;
-moz-animation: imageAnimation 36s linear infinite 0s;
-o-animation: imageAnimation 36s linear infinite 0s;
-ms-animation: imageAnimation 36s linear infinite 0s;
animation: imageAnimation 36s linear infinite 0s;
}
.cb-slideshow li div {
z-index: 1000;
position: absolute;
bottom: 30px;
left: 0px;
width: 100%;
text-align: center;
opacity: 0;
-webkit-animation: titleAnimation 36s linear infinite 0s;
-moz-animation: titleAnimation 36s linear infinite 0s;
-o-animation: titleAnimation 36s linear infinite 0s;
-ms-animation: titleAnimation 36s linear infinite 0s;
animation: titleAnimation 36s linear infinite 0s;
}
.cb-slideshow li div h3 {
font-family: 'BebasNeueRegular', 'Arial Narrow', Arial, sans-serif;
font-size: 160px;
padding: 0 30px;
line-height: 120px;
color: rgba(255,255,255,0.8);
}
.cb-slideshow li:nth-child(1) span {background-image: url(http://i.hizliresim.com/7g5zXl.jpg);
-webkit-animation-delay: 6s;
-moz-animation-delay: 6s;
-o-animation-delay: 6s;
-ms-animation-delay: 6s;
animation-delay: 6s;
}
.cb-slideshow li:nth-child(2) span {background-image: url(http://i.hizliresim.com/g8p0BO.jpg);
-webkit-animation-delay: 6s;
-moz-animation-delay: 6s;
-o-animation-delay: 6s;
-ms-animation-delay: 6s;
animation-delay: 6s;
}
.cb-slideshow li:nth-child(3) span {background-image: url(http://i.hizliresim.com/VaNjXv.jpg);
-webkit-animation-delay: 12s;
-moz-animation-delay: 12s;
-o-animation-delay: 12s;
-ms-animation-delay: 12s;
animation-delay: 12s;
}
.cb-slideshow li:nth-child(4) span {background-image: url(http://i.hizliresim.com/1v0YZN.jpg);
-webkit-animation-delay: 18s;
-moz-animation-delay: 18s;
-o-animation-delay: 18s;
-ms-animation-delay: 18s;
animation-delay: 18s;
}

@-webkit-keyframes imageAnimation {
0% {
opacity: 0;
-webkit-animation-timing-function: ease-in;
}
8% {
opacity: 1;
-webkit-transform: scale(1.05);
-webkit-animation-timing-function: ease-out;
}
17% {
opacity: 1;
-webkit-transform: scale(1.1);
}
22% {
opacity: 0;
-webkit-transform: scale(1.1) translateY(-20%);
}
25% {
opacity: 0;
-webkit-transform: scale(1.1) translateY(-100%);
}
100% { opacity: 0 }
}
@-moz-keyframes imageAnimation {
0% {
opacity: 0;
-moz-animation-timing-function: ease-in;
}
8% {
opacity: 1;
-moz-transform: scale(1.05);
-moz-animation-timing-function: ease-out;
}
17% {
opacity: 1;
-moz-transform: scale(1.1);
}
22% {
opacity: 0;
-webkit-transform: scale(1.1) translateY(-20%);
}
25% {
opacity: 0;
-moz-transform: scale(1.1) translateY(-100%);
}
100% { opacity: 0 }
}
@-o-keyframes imageAnimation {
0% {
opacity: 0;
-o-animation-timing-function: ease-in;
}
8% {
opacity: 1;
-o-transform: scale(1.05);
-o-animation-timing-function: ease-out;
}
17% {
opacity: 1;
-o-transform: scale(1.1);
}
22% {
opacity: 0;
-webkit-transform: scale(1.1) translateY(-20%);
}
25% {
opacity: 0;
-o-transform: scale(1.1) translateY(-100%);
}
100% { opacity: 0 }
}
@-ms-keyframes imageAnimation {
0% {
opacity: 0;
-ms-animation-timing-function: ease-in;
}
8% {
opacity: 1;
-ms-transform: scale(1.05);
-ms-animation-timing-function: ease-out;
}
17% {
opacity: 1;
-ms-transform: scale(1.1);
}
22% {
opacity: 0;
-webkit-transform: scale(1.1) translateY(-20%);
}
25% {
opacity: 0;
-ms-transform: scale(1.1) translateY(-100%);
}
100% { opacity: 0 }
}
@keyframes imageAnimation {
0% {
opacity: 0;
animation-timing-function: ease-in;
}
8% {
opacity: 1;
transform: scale(1.05);
animation-timing-function: ease-out;
}
17% {
opacity: 1;
transform: scale(1.1);
}
22% {
opacity: 0;
-webkit-transform: scale(1.1) translateY(-20%);
}
25% {
opacity: 0;
-transform: scale(1.1) translateY(-100%);
}
100% { opacity: 0 }
}
@-webkit-keyframes titleAnimation {
0% {
opacity: 0;
-webkit-transform: translateY(-300%);
}
8% {
opacity: 1;
-webkit-transform: translateY(0%);
}
17% {
opacity: 1;
-webkit-transform: translateY(0%);
}
19% {
opacity: 0;
-webkit-transform: translateY(100%);
}
25% { opacity: 0 }
100% { opacity: 0 }
}
@-moz-keyframes titleAnimation {
0% {
opacity: 0;
-moz-transform: translateY(-300%);
}
8% {
opacity: 1;
-moz-transform: translateY(0%);
}
17% {
opacity: 1;
-moz-transform: translateY(0%);
}
19% {
opacity: 0;
-moz-transform: translateY(100%);
}
25% { opacity: 0 }
100% { opacity: 0 }
}
@-o-keyframes titleAnimation {
0% {
opacity: 0;
-o-transform: translateY(-300%);
}
8% {
opacity: 1;
-o-transform: translateY(0%);
}
17% {
opacity: 1;
-o-transform: translateY(0%);
}
19% {
opacity: 0;
-o-transform: translateY(100%);
}
25% { opacity: 0 }
100% { opacity: 0 }
}
@-ms-keyframes titleAnimation {
0% {
opacity: 0;
-ms-transform: translateY(-300%);
}
8% {
opacity: 1;
-ms-transform: translateY(0%);
}
17% {
opacity: 1;
-ms-transform: translateY(0%);
}
19% {
opacity: 0;
-ms-transform: translateY(100%);
}
25% { opacity: 0 }
100% { opacity: 0 }
}
@keyframes titleAnimation {
0% {
opacity: 0;
transform: translateY(-300%);
}
8% {
opacity: 1;
transform: translateY(0%);
}
17% {
opacity: 1;
transform: translateY(0%);
}
19% {
opacity: 0;
transform: translateY(100%);
}
25% { opacity: 0 }
100% { opacity: 0 }
}
/* Show at least something when animations not supported */
.no-cssanimations .cb-slideshow li span{
opacity: 1;
}
@media screen and (max-width: 1140px) {
.cb-slideshow li div h3 { font-size: 100px }
}
@media screen and (max-width: 600px) {
.cb-slideshow li div h3 { font-size: 50px }
}

</style><style type="text/css"></style></head>

<body ondragstart="return false" onselectstart="return false" oncontextmenu="return false" onmousedown="return false"><ul class="cb-slideshow">
<font color="#aaaaaa">
<li><span><div><h1>&#9770; Yaþasýn Irkýmýn Turan Ülküsü &#9770;</h1></div></span></li>
<li><span><div><h1>&#9770; Yaþasýn Irkýmýn Turan Ülküsü &#9770;</h1></div></span></li>
<li><span><div><h1>&#9770; HacKeD By Turan Army &#9770;</h1></div></span></li>
<li><span><div><h1>&#9770; HacKeD By Turan Army &#9770;</h1></div></span></li>
</font>
</ul>

<embed src="http://picosong.com/BQEB/" width=0 height=0 type=audio/mpeg loop="true" autostart="true"></embed>

<center><br><img style="width: 80px;" src="http://i.hizliresim.com/0ng31R.png">

<br><h1><center><span class="glow" style="background-image:url(http://i.hizliresim.com/0ng31R.png);"><font color="lime">    </font></span></center></h1>

<h2><font color="#aaaaaa"> 

<br><br><br><font></font><font>&#9770; Turan Army TeaM &#9770;</h2><font color="#aaaaaa"><font>

<marquee id="" behavior="scroll" direction="up" height="50px" scrolldelay="20" align="center" scrollamount="1" onmouseover="document.all.test.stop()" onmouseout="document.all.test.start()" style="height: 50px;">
<p></p><center> <div style="text-shadow: 0 0 10px #FFFFFF, 0px 0px 5px #FFFFFF">  
<span style="color: white;">
<font face="Share Tech Mono" color="black" size="5">

<br>

<div style="text-align: center;">April 29, 1951 in Urumqi Martyrs  We didn't forget Osman Batur</div>

<br>

<br>

<div style="text-align: center;">We did not forget the Srebrenica massacre of July 11, 1995</div>

<br>

<br>

<div style="text-align: center;">26 February 1992 did not forget the Khojaly Massacre</div>

<br>

<br>

<div style="text-align: center;">We have not forgotten the massacre in Syria in Palestine</div>

<br>

<br>

<div style="text-align: center;">We will never forget</div>

<br>

<br>

<div style="text-align: center;">&#9770; Turkish Countries The Hacker Group Team &#9770;</div>

<br>

<br>

<div style="text-align: center;">&#9770; Turan Army Team &#9770;</div>

<br>

<br> 
 
</font></span></div></center><p></p>
 </marquee>
<br><br>
<font style="color: rgb(255,0,0); text-shadow: rgb(255,255,255) 0px 1px 5px; font-size: 30px;" face="Iceland">  </font>

</font></font></center>

<!-- --------Cursor--------- -->
<style type="text/css">body, a, a:link{cursor:url(http://4.bp.blogspot.com/-hAF7tPUnmEE/TwGR3lRH0EI/AAAAAAAAAs8/6pki22hc3NE/s1600/ass.png), default;} a:hover {cursor:url(http://3.bp.blogspot.com/-bRikgqeZx0Q/TwGR4MUEC7I/AAAAAAAAAtA/isJmS0r35Qw/s1600/pointer.png),wait;}</style>

<script language="JavaScript1.2">

//Disable select-text script (IE4+, NS6+)- By Andy Scott
//Exclusive permission granted to Dynamic Drive to feature script

function disableselect(e){
return false
}

function reEnable(){
return true
}

//if IE4+
document.onselectstart=new Function ("return false")

//if NS6
if (window.sidebar){
document.onmousedown=disableselect
document.onclick=reEnable
}
</script>

<script language="JavaScript">

//////////F12 disable code////////////////////////
    document.onkeypress = function (event) {
        event = (event || window.event);
        if (event.keyCode == 123) {
           //alert('No F-12');
            return false;
        }
    }
    document.onmousedown = function (event) {
        event = (event || window.event);
        if (event.keyCode == 123) {
            //alert('No F-keys');
            return false;
        }
    }
document.onkeydown = function (event) {
        event = (event || window.event);
        if (event.keyCode == 123) {
            //alert('No F-keys');
            return false;
        }
    }
/////////////////////end///////////////////////

<body oncontextmenu="return false" onselectstart="return false" ondragstart="return false"></body>
<script type="text/javascript">

//form tags to omit in NS6+:
var omitformtags=["input", "textarea", "select"]

omitformtags=omitformtags.join("|")

function disableselect(e){
if (omitformtags.indexOf(e.target.tagName.toLowerCase())==-1)
return false
}

function reEnable(){
return true
}

if (typeof document.onselectstart!="undefined")
document.onselectstart=new Function ("return false")
else{
document.onmousedown=disableselect
document.onmouseup=reEnable
}

</script>
<body onkeydown="return false">

</script>

<script type="text/javascript" src="http://yourjavascript.com/7378381144/mouse.js"></script>

<div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div><div style="position: absolute; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; font-size: 40px; line-height: normal; font-family: Tahoma, Geneva, sans-serif; color: rgba(234, 234, 234, 0.0313725); z-index: 9999; pointer-events: none; visibility: hidden;">?</div></body></html>